/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_1 = {
  TpToken: '0x6c0c5340c07b895823D860A0e04E6B9d263EC695',
  TermPool: '0x5CCA7F4bdafFaaB29bA99574ac4357fdBD349e36',
  TermPoolFactory: '0x91a4a196Aa25058E523b077A22df420D6aA2e60E',
  ProxyAdmin: '0x1D881611e48C806606d59c1591795514805016e2'
}