/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_1101 = {
  TermPoolFactory: '0x04DF6f15a8c2fE4BF2E7c5CC4e4d7c7DfdCd4445',
  TermPool: '0x1c1c72436493D8C93E54Ac65a19E863cdAD34720',
  TpToken: '0x78DbeE8830A2460b8279E7f15cc8f7FaD3382D16',
  ProxyAdmin: '0xBeA0606D1e4d873DB7F7d8be4373fbedfde34A94'
}