/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_11155111 = {
  TermPoolFactory: '0x59137c2C6f3dFc38BBad50515A63A120AF33d2B5',
  TermPool: '0x6F70641D0eBe9F2FCe8Cef0159Fec3214267A93B',
  TpToken: '0x411F9Fd74A8FE25A428A3863093BD3C0a462a067'
}