/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_137 = {
  TermPoolFactory: '0xc3d7f86CF3a9716eA17972390FF22452d54D35a7',
  TermPool: '0xC510d10e38DA40456e8b55Db327E956bdDaD25bd',
  TpToken: '0x625e7fEdCE0ef3343080154180004CF12dC7471C',
  ProxyAdmin: '0xa3badd653426d61f88396d6d96e1b7aafb16d74e'
}