/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_80001 = {
  TermPoolFactory: '0x16cb0DE825a964ca9e8d3Ad79FC356fd938D4d39',
  TermPool: '0xf42cB4aFBC554dd956EF5625694AEEdD52a0B739',
  TpToken: '0xBA4741a31c7881c8cf99683fb40a89929610BBb6'
}