/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_1 } from './1'
import { ContractAddresses_1101 } from './1101'
import { ContractAddresses_11155111 } from './11155111'
import { ContractAddresses_137 } from './137'
import { ContractAddresses_80001 } from './80001'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  1: ContractAddresses_1,
  1101: ContractAddresses_1101,
  11155111: ContractAddresses_11155111,
  137: ContractAddresses_137,
  80001: ContractAddresses_80001
}